### ISSUE TITLE
Solve Q15 , Q16 , Q17 and Q18

### ISSUE THREAD

**Issue by UtkarshDeoli** [UtkarshDeoli/3rd-Sem-Lab-Programs#3]
15. Create base class with attributes name, age and roll_number. Consider name as private, 
age as protected, and roll_number as public. Write various child programs that inherit 
base class in different access modes like private protected and public and show the 
accessibility of various attributes. 

16. Write a Base class having two attributes int x, int y. Write child class having void 
sum(int x, int y) function to add two provided values. You have to initialize base class’s 
attributes with the help of child class object and then use sum method to add the values. 
Also write a show() method in child to show the result. 
Hint: Use parameterized constructor. 

17. Write a program to copy the value of one object to another. 

18. Write a program to demonstrate diamond’s problem. Also update the same program to 
resolve it. 

@RohitChauhan98

**Comment by UtkarshDeoli** [comment]
@RohitChauhan98  Message here then only i will be able to assign you

**Comment by RohitChauhan98** [comment]
hello assign me

**Comment by UtkarshDeoli** [comment]
The issue was solved #4
